//
// Created by Jorg on 09/02/15.
// Copyright (c) 2015 JENNIUS LTD. All rights reserved.
//

import Foundation

public class ConversationResources: ScriptResources {
    public override init(randomizer: IRandomizer) {
        super.init(randomizer: randomizer)
        add(parameter: "felmaleCelebrity", withValues: ["Taylor Swift",
                                                        "Zoe Saldana",
                                                        "Ariana Grande",
                                                        "Hilary Duff",
                                                        "Britney Spears",
                                                        "Lea Michele",
                                                        "Jennifer Lawrence",
                                                        "Michelle Keegan",
                                                        "Rihanna",
                                                        "Emily Ratajkowski",
                                                        "Kaley Cuoco",
                                                        "Mila Kunis",
                                                        "Beyonce",
                                                        "Lucy Mecklenburgh",
                                                        "Nicole Scherzinger",
                                                        "Scarlett Johansson",
                                                        "Cate Blanchett",
                                                        "Lupita Nyong'o",
                                                        "Emma Stone",
                                                        "Keira Knightley",
                                                        "Jessica Ennis-Hill",
                                                        "Kate Winslet",
                                                        "Angelina Jolie",
                                                        "Nigella Lawson",
                                                        "Amy Willerton",
                                                        "Kelly Brook",
                                                        "Mel Clarke",
                                                        "Georgia Salpa",
                                                        "Margot Robbie",
                                                        "Jorgie Porter",
                                                        "Megan Fox",
                                                        "Susanna Reid",
                                                        "Kendall Jenner",
                                                        "Jenna-Louise Coleman",
                                                        "Amy Adams",
                                                        "Zooey Deschanel",
                                                        "Rita Ora",
                                                        "Jennifer Aniston",
                                                        "Holly Willoughby",
                                                        "Kim Kardashian",
                                                        "Alison Brie",
                                                        "Kate Moss",
                                                        "Meagan Good",
                                                        "Amanda Seyfried",
                                                        "Kate Middleton",
                                                        "Pippa Middleton",
                                                        "Carmen Electra",
                                                        "Emily Blunt",
                                                        "Lois Griffin from Family Guy",
                                                        "Sandra Bullock"])
        add(parameter: "maleCelebrity", withValues: ["Kanye West",
                                                     "Jay-Z",
                                                     "Henry Cavill",
                                                     "Robert Pattinson",
                                                     "Liam Hemsworth",
                                                     "Tom Hiddleston",
                                                     "Benedict Cumberbatch",
                                                     "Harry Styles",
                                                     "Chris Hemsworth",
                                                     "Idris Elba",
                                                     "Jamie Campbell Bower",
                                                     "Justin Bieber",
                                                     "Charlie Hunnam",
                                                     "Ian Somerhalder",
                                                     "Matt Bomer",
                                                     "Johnny Depp",
                                                     "Olly Murs",
                                                     "Michael Fassbender",
                                                     "Channing Tatum",
                                                     "Rafa Nadal",
                                                     "Matt Smith",
                                                     "Robert Downey Jnr",
                                                     "David Beckham",
                                                     "Hugh Jackman",
                                                     "Orlando Bloom",
                                                     "Josh Hutcherson",
                                                     "Paul Wesley",
                                                     "Zayn Malik",
                                                     "Pharrell Williams",
                                                     "Zac Efron",
                                                     "Ryan Gosling",
                                                     "Taylor Lautner",
                                                     "James Franco",
                                                     "Liam Payne",
                                                     "Tinie Tempah",
                                                     "Kit Harington",
                                                     "Alex Turner",
                                                     "Tom Hardy",
                                                     "Tom Daley",
                                                     "Nathan Sykes",
                                                     "Justin Timberlake",
                                                     "Daniel Craig",
                                                     "Andy Murray",
                                                     "Brad Pitt",
                                                     "Ashton Kutcher",
                                                     "George Clooney"])
        add(parameter: "food", withValues: ["ice cream",
                                            "wienerschnitzel",
                                            "samosas",
                                            "a chocolate fondue",
                                            "lasagne",
                                            "cheese burgers"])
        add(parameter: "place", withValues: ["Machu Picchu",
                                             "the toilet",
                                             "Llanfairpwllgwyngyll",
                                             "Mars",
                                             "Abu Dhabi"])


    }
}
