# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target :FoodHero do
    pod "Typhoon"
    pod "LinqToObjectiveC"
    pod "ReactiveCocoa"
    pod "UIImageViewAligned", :path => './../UIImageViewAligned'
    pod "SORelativeDateTransformer"
    # pod 'Wit', '~> 4.0.0'
    pod 'Wit',  :path => './../../wit-ios-sdk'
    pod 'Google-Maps-iOS-SDK'
end

target :FoodHeroTests do
    pod 'OCHamcrest'
    pod 'XCAsyncTestCase'
end

target :FoodHeroIntegrationsTests do
    pod 'OCHamcrest'
    pod 'XCAsyncTestCase'
end


