# Uncomment this line to define a global platform for your project

platform :ios, "8.0"

target :FoodHero do
    pod "Typhoon"
    pod "LinqToObjectiveC"
    pod "ReactiveCocoa"
    pod "UIImageViewAligned", :path => './../UIImageViewAligned'
end

target :FoodHeroTests do
    pod 'OCHamcrest', '~> 4.0'
    pod 'XCAsyncTestCase'
end

target :FoodHeroIntegrationsTests do
    pod 'OCHamcrest', '~> 4.0'
    pod 'XCAsyncTestCase'
end


